const PDFDocument = require("pdfkit");
const fs          = require("fs");
const path        = require("path");
const os          = require("os");

const execute = async (actionType, config, credentials) => {
  switch (actionType) {
    case "generate_pdf": return await generatePDF(config);
    default: throw new Error(`Unknown PDF action: ${actionType}`);
  }
};

const generatePDF = async (config) => {
  const { template = "invoice", variables = {}, outputName = "document.pdf" } = config;

  // Create temp file
  const tmpDir  = os.tmpdir();
  const outPath = path.join(tmpDir, `flowbridge_${Date.now()}_${outputName}`);

  await new Promise((resolve, reject) => {
    const doc  = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outPath);

    doc.pipe(stream);

    switch (template) {
      case "invoice": buildInvoice(doc, variables); break;
      case "receipt": buildReceipt(doc, variables); break;
      case "report":  buildReport(doc, variables);  break;
      default:        buildCustom(doc, variables, config.html); break;
    }

    doc.end();
    stream.on("finish", resolve);
    stream.on("error",  reject);
  });

  const stats   = fs.statSync(outPath);
  const base64  = fs.readFileSync(outPath).toString("base64");

  // Cleanup temp file
  fs.unlinkSync(outPath);

  console.log(`✅ PDF generated — ${outputName} (${stats.size} bytes)`);
  return {
    success:    true,
    fileName:   outputName,
    base64,
    size:       stats.size,
    template,
    message:    "PDF generated successfully",
  };
};

// ── INVOICE TEMPLATE ──────────────────────────────────────────
const buildInvoice = (doc, vars) => {
  const {
    company_name    = "FlowBridge",
    company_address = "",
    invoice_number  = "INV-001",
    invoice_date    = new Date().toLocaleDateString("en-IN"),
    customer_name   = "Customer",
    customer_email  = "",
    customer_address= "",
    items           = [],
    subtotal        = 0,
    tax             = 0,
    total           = 0,
    currency        = "INR",
    notes           = "",
  } = vars;

  // Header
  doc.fontSize(24).font("Helvetica-Bold").text(company_name, 50, 50);
  if (company_address) doc.fontSize(10).font("Helvetica").text(company_address, 50, 80);

  // Invoice title
  doc.fontSize(20).font("Helvetica-Bold").text("INVOICE", 400, 50, { align: "right" });
  doc.fontSize(10).font("Helvetica")
    .text(`Invoice #: ${invoice_number}`, 400, 80, { align: "right" })
    .text(`Date: ${invoice_date}`, 400, 95, { align: "right" });

  // Divider
  doc.moveTo(50, 120).lineTo(550, 120).stroke();

  // Bill to
  doc.fontSize(12).font("Helvetica-Bold").text("Bill To:", 50, 140);
  doc.fontSize(10).font("Helvetica")
    .text(customer_name,    50, 158)
    .text(customer_email,   50, 173)
    .text(customer_address, 50, 188);

  // Items table header
  let y = 230;
  doc.fontSize(11).font("Helvetica-Bold")
    .text("Item",        50,  y)
    .text("Qty",        300,  y)
    .text("Price",      370,  y)
    .text("Amount",     460,  y);
  doc.moveTo(50, y + 18).lineTo(550, y + 18).stroke();
  y += 28;

  // Items
  doc.fontSize(10).font("Helvetica");
  const itemList = Array.isArray(items) ? items : [];
  itemList.forEach(item => {
    doc.text(item.name   || "",   50, y)
       .text(String(item.qty || 1),   300, y)
       .text(`${currency} ${item.price || 0}`, 370, y)
       .text(`${currency} ${item.amount || 0}`, 460, y);
    y += 20;
  });

  // Totals
  doc.moveTo(50, y + 5).lineTo(550, y + 5).stroke();
  y += 20;
  doc.font("Helvetica")
    .text(`Subtotal: ${currency} ${subtotal}`, 370, y)
    .text(`Tax: ${currency} ${tax}`,           370, y + 18);
  doc.font("Helvetica-Bold")
    .text(`Total: ${currency} ${total}`,       370, y + 36);

  // Notes
  if (notes) {
    doc.fontSize(9).font("Helvetica").text(`Notes: ${notes}`, 50, y + 60);
  }

  // Footer
  doc.fontSize(8).font("Helvetica")
    .text("Generated by FlowBridge", 50, 750, { align: "center", width: 500 });
};

// ── RECEIPT TEMPLATE ──────────────────────────────────────────
const buildReceipt = (doc, vars) => {
  const {
    business_name   = "FlowBridge",
    receipt_number  = "REC-001",
    date            = new Date().toLocaleDateString("en-IN"),
    customer_name   = "Customer",
    amount          = 0,
    payment_method  = "Online",
    currency        = "INR",
    description     = "",
  } = vars;

  doc.fontSize(22).font("Helvetica-Bold").text("RECEIPT", { align: "center" });
  doc.fontSize(14).font("Helvetica").text(business_name, { align: "center" });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(11).font("Helvetica")
    .text(`Receipt #: ${receipt_number}`)
    .text(`Date: ${date}`)
    .text(`Customer: ${customer_name}`)
    .text(`Payment Method: ${payment_method}`);

  if (description) doc.text(`Description: ${description}`);

  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(16).font("Helvetica-Bold")
    .text(`Amount Paid: ${currency} ${amount}`, { align: "center" });

  doc.moveDown(2);
  doc.fontSize(9).font("Helvetica")
    .text("Thank you for your payment!", { align: "center" })
    .text("Generated by FlowBridge", { align: "center" });
};

// ── REPORT TEMPLATE ───────────────────────────────────────────
const buildReport = (doc, vars) => {
  const {
    title       = "Report",
    date        = new Date().toLocaleDateString("en-IN"),
    prepared_by = "FlowBridge",
    sections    = [],
    summary     = "",
  } = vars;

  doc.fontSize(22).font("Helvetica-Bold").text(title, { align: "center" });
  doc.fontSize(10).font("Helvetica")
    .text(`Date: ${date} | Prepared by: ${prepared_by}`, { align: "center" });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  if (summary) {
    doc.fontSize(12).font("Helvetica-Bold").text("Summary");
    doc.fontSize(10).font("Helvetica").text(summary);
    doc.moveDown();
  }

  const sectionList = Array.isArray(sections) ? sections : [];
  sectionList.forEach(section => {
    doc.fontSize(13).font("Helvetica-Bold").text(section.title || "");
    doc.fontSize(10).font("Helvetica").text(section.content || "");
    doc.moveDown();
  });

  doc.fontSize(8).font("Helvetica")
    .text("Generated by FlowBridge", 50, 750, { align: "center", width: 500 });
};

// ── CUSTOM TEMPLATE ───────────────────────────────────────────
const buildCustom = (doc, vars, htmlContent) => {
  // Simple text render for custom template
  const content = htmlContent
    ? htmlContent.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim()
    : JSON.stringify(vars, null, 2);

  doc.fontSize(12).font("Helvetica").text(content, { width: 500 });
};

module.exports = { execute };
